packet03-redirecting: remove refs to tx_port map from assignment 04
xdp-project/xdp-tutorial pull request #282
Opened 2022-04-06 15:47 UTC by mdr78

Looking up the tx_port map for a 1:1 mapping in packet 03 assignment 04 is pointless. If bpf_fib_lookup returns a successful lookup, it is much simplier and more obvious to directly call bpf_redirect with the information from the fib without the map lookup. 

Other minor documentation fixes also included.

2022-04-07 12:39 UTC, tohojo requested changes
I'm okay with moving to `bpf_redirect()` instead of `bpf_redirect_map()` - there used to be a performance difference, but we fixed that.

However, you'll need to also update the text of the packet03 assignment (in README,org) to match the new code :)

2022-04-08 13:19 UTC, tohojo commented on packet03-redirecting/xdp_prog_kern.c
> +		/* action = bpf_redirect(???, 0); */
There's another reference to bpf_redirect_map three lines above this one :)

2022-04-08 13:56 UTC, mdr78 commented
Hi,

PR has been updated with the requested changes.

Ray K

2022-04-09 13:23 UTC, tohojo requested changes
Found one other issue, but hopefully this is the last one :)

2022-04-09 13:23 UTC, tohojo commented on packet-solutions/xdp_prog_user.c
> -			bpf_map_update_elem(map_fd, &i, &i, 0);
Hmm, you should probably also update the kernel code to call `bpf_redirect()` instead of `bpf_redirect_map()` :)

2022-04-15 15:49 UTC, mdr78 commented
> Found one other issue, but hopefully this is the last one :)

Resolved, apologies for missing that.

2022-04-15 19:51 UTC, tohojo approved these changes
Alright, looks good. Thanks for the fixes! :)

2022-04-15 19:52 UTC, merged