Update setup dependencies page for aarch64/arm64
xdp-project/xdp-tutorial pull request #370
Opened 2023-09-11 18:17 UTC by sachintiptur

For ARM64/AArch64 based systems, as linux header files reside under architecture specific directories, need to create soft links. This PR is for documenting the same.

2023-09-12 14:03 UTC, tohojo commented
Rather than instructing people to make global changes to their file system, it is better to update the configure script to automatically add the right directory to the include path. We already have such a check in the xdp-tools configure script (look for `ARCH_INCLUDES`, so it should just be a matter of porting that to the tutorial configure.

Note, that I'm not quite sure if the way we build the arch tuple is actually right in the xdp-tools configure; we may need to switch it to use `gcc -print-multiarch` or something similar instead. I don't have an ARM box to test on, though...

2023-09-13 20:29 UTC, tohojo requested changes
A few nits, but otherwise definitely on the right track. I don't suppose you'd care to open a PR for the bpf-examples repo as well? :)

2023-09-13 20:29 UTC, tohojo commented on configure
> +            idir="${dir}/$($CC -print-multiarch)"
Same comment as on the xdp-tools PR :)

2023-09-13 20:29 UTC, tohojo commented on configure
> +    compile_err=$($CLANG -target bpf -I/usr/include/$($CC -print-multiarch) -c $TMPDIR/bpf_use_errno_test.c 2>&1)
Couldn't this just reuse `$ARCH_INCLUDES`? Just make it a global var in the configure script...

2023-09-20 20:30 UTC, sachintiptur commented
> A few nits, but otherwise definitely on the right track. I don't suppose you'd care to open a PR for the bpf-examples repo as well? :)

Sure, will take care there too :)

2023-09-21 21:25 UTC, tohojo approved these changes

2023-09-21 21:28 UTC, tohojo commented
Could you please squash the commits? And remove the gcc-multilib package from the instructions in setup_dependencies.org as well while you're at it? :)

2023-09-23 10:51 UTC, tohojo approved these changes

2023-09-23 10:51 UTC, tohojo commented
Thanks for doing all of these! :)

2023-09-23 10:51 UTC, merged