Update setup_dependencies.org
xdp-project/xdp-tutorial pull request #381
Opened 2023-12-18 17:00 UTC by rmahique

- Added a section with the instructions to generate the necessary files mentioned and used in the exercises.
- Added missing dependencies

2023-12-19 12:59 UTC, rmahique commented on setup_dependencies.org
> +* Extra tools
make will fail if bpftool is not installed, that is why i changed from recommended to extra

2024-01-04 19:47 UTC, tohojo requested changes
Thank you for the additions! A few comments below, but overall looks like a nice update :)

2024-01-04 19:47 UTC, tohojo commented on setup_dependencies.org
> +git clone git@github.com:xdp-project/xdp-tutorial.git
We use the https URL everywhere else; let's do the same here...

2024-01-04 19:47 UTC, tohojo commented on setup_dependencies.org
> + $ sudo apt install clang llvm libelf-dev libpcap-dev build-essential libc6-dev-i386
Why is this needed?

2024-01-04 19:47 UTC, tohojo commented on setup_dependencies.org
> + $ sudo make
Absolutely do not run `make` with sudo!

2024-01-04 19:47 UTC, tohojo commented on setup_dependencies.org
> +git clone git@github.com:xdp-project/xdp-tutorial.git
Also, if we're adding this, I think it's better to add the `--recurse-submodules` switch here (and get rid of it below), then rewrite the text below to explain that the `git submodule update` command is only needed if `--recurse-submodules` was not used in the initial clone command...

2024-01-19 05:05 UTC, rmahique commented on setup_dependencies.org
> + $ sudo apt install clang llvm libelf-dev libpcap-dev build-essential libc6-dev-i386
I found it was missing on the standard debian install i did

2024-01-19 11:08 UTC, tohojo commented on setup_dependencies.org
> + $ sudo apt install clang llvm libelf-dev libpcap-dev build-essential libc6-dev-i386
Right, but I mean, what breaks if it's not present?

2024-01-25 14:45 UTC, rmahique commented on setup_dependencies.org
> + $ sudo apt install clang llvm libelf-dev libpcap-dev build-essential libc6-dev-i386
Running ./configure will fail and ask for it:

```shell

$ ./configure
clang: 16.0.6 (19)
libbpf support: submodule
ELF support: yes
zlib support: yes
libxdp support: system
*** ERROR - Clang BPF-prog cannot include <errno.h>
          - Install missing userspace header file

Compile error: In file included from config.GwBzhM/bpf_use_errno_test.c:1:
In file included from /usr/include/errno.h:25:
In file included from /usr/include/features.h:514:
/usr/include/x86_64-linux-gnu/gnu/stubs.h:7:11: fatal error: 'gnu/stubs-32.h' file not found
# include <gnu/stubs-32.h>
          ^~~~~~~~~~~~~~~~
1 error generated.

 On Fedora install:
   dnf install glibc-devel.i686
 On Debian install:
   apt install libc6-dev-i386

```

2024-01-30 12:14 UTC, tohojo commented on setup_dependencies.org
> + $ sudo apt install clang llvm libelf-dev libpcap-dev build-essential libc6-dev-i386
Huh, didn't even realise that was in there. Alright, cool :)

2024-01-30 12:15 UTC, merged

2025-01-21 02:21 UTC, sys0613 commented on setup_dependencies.org
> + $ sudo apt install clang llvm libelf-dev libpcap-dev build-essential libc6-dev-i386
how to deal this

clang: 13.0.1 (UnionTech OS 13.0.1-2.0.2.module+uelc20+911+09ad4a12.01)
libbpf support: submodule
ELF support: yes
zlib support: yes
libxdp support: submodule
Configuring libxdp to use our libbpf submodule
Found clang binary 'clang' with version 13 (from 'clang version 13.0.1 (UnionTech OS 13.0.1-2.0.2.module+uelc20+911+09ad4a12.01)')
not using emacs:
using bpftool v7.5.0
libbpf support: custom v1.2.0
  perf_buffer__consume support: yes
  btf__load_from_kernel_by_id support: yes
  btf__type_cnt support: yes
  bpf_object__next_map support: yes
  bpf_object__next_program support: yes
  bpf_program__insn_cnt support: yes
  bpf_program__type support: yes
  bpf_program__flags support: yes
  bpf_program__expected_attach_type support: yes
  bpf_map_create support: yes
  perf_buffer__new_raw support: yes
  bpf_xdp_attach support: yes
  bpf_map__set_autocreate support: yes
  bpf_prog_test_run_opts support: yes
  bpf_xdp_query support: yes
zlib support: yes
ELF support: yes
pcap support: yes
secure_getenv support: yes
cap-ng support: no
*** ERROR - Clang BPF-prog cannot include <errno.h>
          - Install missing userspace header file

Compile error: In file included from config.0WzjSh/bpf_use_errno_test.c:1:
In file included from /usr/include/errno.h:25:
In file included from /usr/include/features.h:462:
/usr/include/gnu/stubs.h:7:11: fatal error: 'gnu/stubs-32.h' file not found
# include <gnu/stubs-32.h>
          ^~~~~~~~~~~~~~~~
1 error generated.

 On Fedora install:
   dnf install glibc-devel.i686
 On Debian install:
   apt install libc6-dev-i386