Add tc_reply_kern_02 program to fix reply packets' source port
xdp-project/xdp-tutorial pull request #401
Opened 2024-03-06 08:31 UTC by bigclouds

As xdp_prog_kern_02.c modifies destination port , this tc program is to fix reply packets.
They needs to work together with xdp_prog_kern_02.

2024-03-06 08:42 UTC, bigclouds commented
@tohojo Hi, please take time to review this PR. Thanks

2024-03-12 09:21 UTC, tohojo requested changes
Some nits, mostly. How did you test this?

2024-03-12 09:21 UTC, tohojo commented on packet-solutions/tc_reply_kern_02.c
> +	struct hdr_cursor nh = { .pos = data };
We follow the netdev "reverse christmas tree" variable ordering, see https://docs.kernel.org/process/maintainer-netdev.html#local-variable-ordering-reverse-xmas-tree-rcs

Please reorder these accordingly...

2024-03-12 09:21 UTC, tohojo commented on packet-solutions/tc_reply_kern_02.c
> +SEC("fix_port_egress")
Custom section names have been deprecated in libbpf. This should be `SEC("tc")`

2024-03-12 09:21 UTC, tohojo commented on packet-solutions/tc_reply_kern_02.c
> +        }
No need for the braces

2024-03-12 09:21 UTC, tohojo commented on packet-solutions/tc_reply_kern_02.c
> +		}
Unnecessary braces

2024-03-12 09:21 UTC, tohojo commented on packet-solutions/tc_reply_kern_02.c
> +		}
Unnecessary braces

2024-03-13 09:02 UTC, bigclouds commented
@tohojo Thanks. All Done.

2024-03-13 14:29 UTC, merged