Update packet03-redirecting/README.org to meet kernel source tree update
xdp-project/xdp-tutorial pull request #409
Opened 2024-03-22 14:42 UTC by shiponcs

[xdp_redirect_map_kern.c](https://github.com/torvalds/linux/blob/v5.14/samples/bpf/xdp_redirect_map_kern.c) is no more present in the current Linux Kernel source tree in GitHub. Starting from [this commit](https://github.com/torvalds/linux/commit/54af769db92a47be8a9d23a4434dbd343b3), the file's name has changed and most of its content has moved to some other files. Therefore, to retain the integrity of the lessons of **xdp-tutorial/packet03-redirecting**, we can point to this file in last stable release tag of Linux Kernel source tree where the file was present. The job was done in this PR.

2024-03-25 19:35 UTC, shiponcs commented
CC: @tohojo

2024-04-12 13:08 UTC, tohojo requested changes
I think it's better to link to where the code has moved to, in xdp-tools: https://github.com/xdp-project/xdp-tools/blob/master/xdp-bench/xdp_redirect_devmap.bpf.c

2024-04-13 17:16 UTC, shiponcs commented
> The file's name has changed and most of its content has moved to some other files.
It is not possible to refer to a particular file.

2024-04-14 18:55 UTC, tohojo approved these changes

2024-04-14 18:56 UTC, merged